### ISSUE TITLE
Recent Post to fix

### ISSUE THREAD

**Issue by KaminoU** [vhessam/laravel-blogger#1]
Hi @vhessam 

in laravel-blogger/src/Views/blogetc/sitewide/recent_posts.blade.php

`@forelse(\WebDevEtc\BlogEtc\Models\BlogEtcPost::orderBy("posted_at","desc")->limit(3)->get() as $post)`

you have to change it to

`@forelse(\WebDevEtc\BlogEtc\Models\BlogEtcPost::where('is_published', '=', 1)->where('posted_at', '<', Carbon\Carbon::now()->format('Y-m-d H:i:s'))->orderBy("posted_at","desc")->limit(3)->get() as $post)`

to only post the last one supposed to be posted =)

Cheers

**Comment by vhessam** [comment]
@KaminoU  many thanks 
this fix is added..
