### ISSUE TITLE
Laravel 8 installation

### ISSUE THREAD

**Issue by mwoszczyna** [vhessam/laravel-blogger#12]
I'm a bit confused. I'm on laravel 8 and have some issue with installation:

> Installation request for hessam/laravel-blogger ^8.0 -> satisfiable by hessam/laravel-blogger[v8.0.0].
>    - Installation request for laravel/framework (locked at v8.5.0, required as ^8.0) -> satisfiable by laravel/framework[v8.5.0].
 >   - hessam/laravel-blogger v8.0.0 requires laravel/framework ~5.8|~6.0|~7.0|~8.0 -> satisfiable by laravel/framework[v8.5.0, 5.8.x-dev, 6.x-dev, 7.x-dev, 8.x-dev, v8.0.0, v8.0.1, v8.0.2, v8.0.3, v8.0.4, v8.1.0, v8.2.0, v8.3.0, v8.4.0].
 >   - Can only install one of: laravel/framework[6.x-dev, 5.7.x-dev].
 >   - Can only install one of: laravel/framework[7.x-dev, 5.7.x-dev].
 >   - Can only install one of: laravel/framework[8.x-dev, 5.7.x-dev].
  >  - Can only install one of: laravel/framework[v8.0.0, 5.7.x-dev].
   > - Can only install one of: laravel/framework[v8.0.1, 5.7.x-dev].
  >  - Can only install one of: laravel/framework[v8.0.2, 5.7.x-dev].
  >  - Can only install one of: laravel/framework[v8.0.3, 5.7.x-dev].
  >  - Can only install one of: laravel/framework[v8.0.4, 5.7.x-dev].
  >  - Can only install one of: laravel/framework[v8.1.0, 5.7.x-dev].
  >  - Can only install one of: laravel/framework[v8.2.0, 5.7.x-dev].
  >  - Can only install one of: laravel/framework[v8.3.0, 5.7.x-dev].
  >  - Can only install one of: laravel/framework[v8.4.0, 5.7.x-dev].
   > - Can only install one of: laravel/framework[v8.5.0, 5.7.x-dev].
   > - Can only install one of: laravel/framework[5.7.x-dev, v8.5.0].
   > - Can only install one of: laravel/framework[5.7.x-dev, v8.5.0].
   > - Can only install one of: laravel/framework[5.8.x-dev, 5.7.x-dev].
   > - Conclusion: install laravel/framework 5.7.x-dev

Why I can't install it?

**Comment by vhessam** [comment]
Hi @mwoszczyna ,
it's be ok if you reinstall it again. Thanks ;)
