### ISSUE TITLE
error while trying to upload an image on add post

### ISSUE THREAD

**Issue by murprakoso** [vhessam/laravel-blogger#13]
TypeError
Argument 1 passed to WebDevEtc\BlogEtc\Controllers\BlogEtcAdminController::getImageFilename() must be of the type string, null given, called in /windows10/Users/Pichan/Documents/Project/blog/vendor/hessam/laravel-blogger/src/Traits/UploadFileTrait.php on line 96

**Comment by vhessam** [comment]
hi,
please check related directories are writable plus check Image upload errors section here: https://github.com/vhessam/laravel-blogger
