### ISSUE TITLE
Categories edit issue without any node . 

### ISSUE THREAD

**Issue by adeshsuryan** [vhessam/laravel-blogger#14]
Hi Team,
the issue has been displaying on each category's edit section . 

![Screenshot from 2020-11-05 20-27-05](https://user-images.githubusercontent.com/887994/98257178-646f1b00-1fa5-11eb-8102-df0e41d5c80f.png)

**Comment by vhessam** [comment]
@adeshsuryan
Hi, thanks for reporting this issue. Would you please draw your category hierarchy and tell me which one do you wanna delete?
many thanks

**Comment by vhessam** [comment]
@adeshsuryan 
I could not generate your issue. Tell me what you did. Many thanks

**Comment by adeshsuryan** [comment]
Hi Team,
I'm sharing with you the error with full details. 
OS and config : 
Ubuntu 18.4, PHP 7.3 
Laravel: 7.x
Issue: The issue has happened when the user edits blog categories the first time. That time we not updating any root categories and that time node looking left and right node etc.

**Comment by vhessam** [comment]
Let me check them.
We have a big release on 1st Dec. Good news wait for it.
