### ISSUE TITLE
Categories parent_id not found

### ISSUE THREAD

**Issue by wast** [vhessam/laravel-blogger#3]
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'parent_id' in 'where clause' (SQL: select * from `blog_etc_categories` where `parent_id` is null) 

Command php artisan vendor:publish --provider="WebDevEtc\BlogEtc\BlogEtcServiceProvider" doesn't copy migrations.

php artisan vendor:publish --provider="WebDevEtc\BlogEtc\BlogEtcServiceProvider"
Copied Directory [/vendor/hessam/laravel-blogger/src/Views/blogetc] To [/resources/views/vendor/blogetc]
Publishing complete.

**Comment by vhessam** [comment]
Hi @wast,
see this link: https://hessam.binshops.com/laravel-blog-package
you should change this file `config/laravel-fulltext.php file change` and edit these fields: exclude_feature_enabled to true and exclude_records_column_name to is_published.

For migration issue, do you have any warning or error while entering `php artisan vendor:publish` command?

thanks for your contribution

**Comment by wast** [comment]
No warnings with php artisan vendor:publish

What I have done was manually copy https://github.com/vhessam/laravel-blogger/blob/master/migrations/2020_05_27_104123_add_parameters_blog_etc_categories_table.php to my project migrations folder and then ran php artisan migrate and it passed.

**Comment by vhessam** [comment]
I tested it, it was ok.
If problem with migrations persists I do testing more.
