### ISSUE TITLE
Disable search feature

### ISSUE THREAD

**Issue by wast** [vhessam/laravel-blogger#6]
![image](https://user-images.githubusercontent.com/9076227/87761578-ff36c480-c811-11ea-962d-1da39041af36.png)

I want to be able to disable search so there is no search frontend.

**Comment by wast** [comment]
Pull request #8  
Check it out

**Comment by vhessam** [comment]
thanks @wast 
OK I'll check it

**Comment by wast** [comment]
Merged #8
