### ISSUE TITLE
Can't change between full post and partial post on index

### ISSUE THREAD

**Issue by wast** [vhessam/laravel-blogger#7]
Instead of 
`<p>{!! mb_strimwidth($post->post_body_output(), 0, 400, "...") !!}</p>`
I want
`<p>{!! $post->post_body_output() !!}</p>`

What do you think if this was configurable?

**Comment by wast** [comment]
#9 check it out

**Comment by vhessam** [comment]
thanks @wast 
let me check it

**Comment by vhessam** [comment]
@wast 
thank you so much, the feature is added no: v7.2.2
